-- ============================================================
-- RECONSTRUCAO DO CATALOGO TSM (standard_id=2)
-- Substitui os 8 topicos genericos / 18 requisitos por
-- 9 protocolos reais TSM / 34 indicadores, conforme os 9
-- arquivos HBR101550001-GMN-RT001_R1_APENDICE_II_TSM_*.xlsx
-- ============================================================
begin;
delete from tsm_assessments where response_id in (select id from tsm_responses where requirement_id in (select id from standard_requirements where standard_id=2));
delete from tsm_responses where requirement_id in (select id from standard_requirements where standard_id=2);
delete from standard_requirements where standard_id=2;
delete from standard_topics where standard_id=2;

with new_topics as (
  insert into standard_topics (standard_id, code, display_order, title, description, color_hex, icon)
  select 2, v.code, v.disp, v.title, v.descr, v.color, v.icon from (values
  ('REJ', 1, 'Gestão de Rejeitos', 'Gestão de Rejeitos (Protocolo TSM)', '#8B5E34', 'trash'),
  ('CLIMA', 2, 'Mudanças Climáticas', 'Mudanças Climáticas (Protocolo TSM)', '#0891B2', 'cloud'),
  ('AGUA', 3, 'Gestão Sustentável de Água', 'Gestão Sustentável de Água (Protocolo TSM)', '#0EA5E9', 'droplet'),
  ('BIODIV', 4, 'Conservação da Biodiversidade', 'Conservação da Biodiversidade (Protocolo TSM)', '#16A34A', 'leaf'),
  ('CRISE', 5, 'Gestão e Comunicação de Crise', 'Gestão e Comunicação de Crise (Protocolo TSM)', '#DC2626', 'alert-triangle'),
  ('DIVERSO', 6, 'Locais de Trabalho Diversos, Equitativos e Inclusivos', 'Locais de Trabalho Diversos, Equitativos e Inclusivos (Protocolo TSM)', '#7C3AED', 'users'),
  ('SEGURO', 7, 'Locais de Trabalho Seguros, Saudáveis e Respeitosos', 'Locais de Trabalho Seguros, Saudáveis e Respeitosos (Protocolo TSM)', '#1D4ED8', 'shield'),
  ('TRABINF', 8, 'Prevenção ao Trabalho Infantil ou Análogo à Escravidão', 'Prevenção ao Trabalho Infantil ou Análogo à Escravidão (Protocolo TSM)', '#BE185D', 'heart'),
  ('COMUNIDADE', 9, 'Relações Comunitárias', 'Relações Comunitárias (Protocolo TSM)', '#D97706', 'users')
  ) as v(code, disp, title, descr, color, icon)
  returning id, code
),
new_reqs as (
  insert into standard_requirements (topic_id, standard_id, code, title, description, guidance, display_order, weight, sub_requirements)
  select nt.id, 2, v.code, v.title, v.descr, v.guidance, v.disp, 1, v.subreqs::jsonb
  from (values
    ('REJ', 'REJ-01', 1, 'Política e Compromisso para Gestão de Rejeitos', 'Estabelecer e comunicar, de forma eficaz, a política e/ou os compromissos que expressam intenção, compromissos e princípios, referentes à gestão de rejeitos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Não foi identificado Sistema de Gestão de Disposição de Rejeitos (SGDR) formalmente estabelecido e implementado para nenhuma das estruturas avaliadas, em conformidade com as diretrizes e requisitos definidos no Guia de Gestão de Rejeitos do TSM.', '[]'),
    ('REJ', 'REJ-02', 2, 'Sistema de Gestão de Rejeitos e Preparação para Emergências', 'Desenvolver e implementar um sistema de gestão de rejeitos de acordo com a estrutura de gestão de rejeitos descrito no Guia de Rejeitos, e desenvolver e testar Planos de Respostas a Emergências (PRE), e Planos de Prevenção e Emergências (PPE), de acordo com o Guia de Rejeitos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): C | Lacunas identificadas: Além da ausência de um SGDR aderente ao Guia de Gestão de Rejeitos do TSM para todas as estruturas, verificou-se que a Célula 02, atualmente em fase de construção, não possui Plano de Ação de Emergência para Barragens (PAEBM) nem Plano de Gestão de Riscos de Barragens de Mineração (PGRBM) formalizados e documentados.', '[{"id": "REJ-02.1", "text": "Revisão Independente"}, {"id": "REJ-02.2", "text": "Objetivos de Desempenho"}, {"id": "REJ-02.3", "text": "Gerenciamento de Conformidade"}, {"id": "REJ-02.4", "text": "Gerenciando Mudanças"}, {"id": "REJ-02.5", "text": "Controles Críticos"}, {"id": "REJ-02.6", "text": "Gestão da Qualidade"}, {"id": "REJ-02.7", "text": "Recursos"}, {"id": "REJ-02.8", "text": "Controle Fnanceiro"}, {"id": "REJ-02.9", "text": "Controle de Informações Documentadas"}, {"id": "REJ-02.10", "text": "Treinamento e Competência"}, {"id": "REJ-02.11", "text": "Comunicações"}, {"id": "REJ-02.12", "text": "Avaliação de Desempenho"}, {"id": "REJ-02.13", "text": "Plano de Resposta a Emergências (PRE)"}, {"id": "REJ-02.14", "text": "Plano de Preparação para Emergências (PPE)"}, {"id": "REJ-02.15", "text": "Abordar riscos de inundação (aplicável se houver risco de inundação de áreas a jusante)"}, {"id": "REJ-02.16", "text": "Testes de PRE e PPE"}]'),
    ('REJ', 'REJ-03', 3, 'Prestação de Contas e Responsabilidade pela Gestão de Rejeitos', 'Assegurar que a responsabilidade pela prestação de contas da gestão de rejeitos esteja atribuída a um Diretor Executivo Responsável (como por exemplo um CEO, COO ou vice-presidente), e que a empresa disponha de uma estrutura de gestão adequada, com recursos disponíveis, capaz de assegurar à empresa que os rejeitos são geridos de forma responsável.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): C | Lacunas identificadas: Para a Célula 02, não foram identificados responsáveis formalmente designados e documentados para a gestão da estrutura. No caso das Barragens Tocantinzinho e Célula 01, embora existam responsáveis indicados, não foram identificados registros documentais que descrevam de forma completa, clara e estruturada as atribuições, responsabilidades e níveis de autoridade de todos os envolvidos.', '[]'),
    ('REJ', 'REJ-04', 4, 'Revisão Anual da Getsão de Rejeitos', 'Realizar revisões anuais em gestão de rejeitos e reportá-las ao dirigente executivo, de modo a garantir a governança corporativa da gestão de rejeitos e assegurar que a empresa permaneça satisfeita com a eficácia das estruturas e dos sistemas organizacionais empregados, bem como com sua aderência às necessidades da organização.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): C | Lacunas identificadas: Não foram identificadas revisões anuais da gestão de rejeitos formalizadas e documentadas para nenhuma das três estruturas, conduzidas em conformidade com as diretrizes, escopo e conteúdo mínimo estabelecidos no Guia de Gestão de Rejeitos referenciado pelo TSM.', '[]'),
    ('REJ', 'REJ-05', 5, 'Manual de Opreação, Manutenção e Monitoramento (OMS)', 'Assegurar que a empresa possui e aplica um manual de OMS específico para a instalação de rejeitos, alinhado ao Guia de OMS, visando apoiar a implementação do sistema de gestão de rejeitos (Indicador 2).', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): C | Lacunas identificadas: A Célula 02 não possui Manual de Operação, Manutenção e Monitoramento (OMS) elaborado. Adicionalmente, os manuais existentes para as Barragens Tocantinzinho e Célula 01 não atendem integralmente ao conteúdo, à abrangência e aos requisitos previstos no Guia de OMS referenciado pelo TSM, demandando adequações.', '[{"id": "REJ-05.1", "text": "Ligações com Outros Sistemas"}, {"id": "REJ-05.2", "text": "Implementação do Manual de OMS"}, {"id": "REJ-05.3", "text": "Revendo e Atualizando o Manual de OMS"}, {"id": "REJ-05.4", "text": "Controle de Informações Documentadas"}, {"id": "REJ-05.5", "text": "Governança de OMS"}, {"id": "REJ-05.6", "text": "Descrição da Instalação de Rejeitos"}, {"id": "REJ-05.7", "text": "Operação"}, {"id": "REJ-05.8", "text": "Manutenção"}, {"id": "REJ-05.9", "text": "Vigilância/Monitoramento"}, {"id": "REJ-05.10", "text": "Vínculos com o Plano de Resposta a Emergências"}]'),
    ('CLIMA', 'CLIMA-01', 1, 'Gestão Corporativa das Mudanças Climáticas', 'Confirmar que os compromissos, governança e processos estão implementados no conselho e em níveis gerenciais para apoio na consideração das implicações das mudanças climáticas nas estratégias de negócios. Este indicador deve ser preenchido no nível corporativo.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Existem lacunas quantitativas para o futuro. O último relatório admite que a meta de redução de emissões para 2030 ainda é uma atividade futura, e não há um compromisso formalizado de "Net Zero" para 2050. Também não foram encontradas evidências de mecanismos financeiros avançados, como o uso de um preço interno de carbono para avaliar investimentos. Na cadeia de valor, embora o diálogo com fornecedores tenha começado, ainda não há critérios climáticos consolidados para compras e seleção de parceiros. Por fim, não há registros de atuação direta junto ao Governo Federal para a definição de planos setoriais de mitigação.', '[]'),
    ('CLIMA', 'CLIMA-02', 2, 'Gestão de Mudanças Climáticas em Instalações', 'Confirmar que sistemas estão implementados em nível de instalação para gerenciamento de energia, emissões de GEE, impactos climáticos físicos e adaptação. Este indicador é apoiado pelo Guia de Adaptação às Mudanças Climáticas para o Setor de Mineração da Associação de Mineração do Canadá - Guide on Climate Change Adaptation for the Mining Sector (MAC).', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: O sistema de gestão de energia e emissões de GEE carece de um mecanismo robusto de verificação independente. Os documentos confirmam que os dados e processos de gestão não foram submetidos a uma auditoria externa. Além disso, não há evidência de que tenha sido realizada uma auditoria interna dedicada especificamente para validar a eficácia e conformidade deste sistema de gestão, o que limita a garantia de integridade dos controles climáticos reportados.

A aplicação do sistema de gestão permanece restrita às operações internas da instalação. Não foram encontrados mecanismos que estendam as diretrizes, metas e monitoramento de energia e GEE para todo o ciclo de vida das atividades, abrangendo fornecedores, clientes e terceiros. Embora a empresa tenha iniciado o mapeamento de emissões indiretas, as práticas de gestão e exigências contratuais climáticas ainda não são aplicadas à cadeia de suprimentos.

A gestão de riscos físicos e adaptação baseia-se estritamente em critérios técnicos e de engenharia, sem incorporar o conhecimento comunitário, cultural ou tradicional local nas avaliações de impacto climático ou no desenho das medidas de adaptação. Adicionalmente, não há registros de colaboração ou parcerias ativas com as Comunidades de Interesse (CDI) ou outras organizações externas voltadas especificamente para a gestão conjunta de impactos climáticos físicos e estratégias de adaptação compartilhada no território.', '[]'),
    ('CLIMA', 'CLIMA-03', 3, 'Metas de Desempenho de Instalações', 'Confirmar que as metas de desempenho de energia e emissões de GEE foram estabelecidas no nível da instalação e que o relatório público anual incorpora os tópicos de energia, emissões de GEE, possíveis impactos climáticos físicos e medidas de adaptação.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): C | Lacunas identificadas: Embora o empreendedor tenha realizado o inventário (o diagnóstico), o Relatório de Sustentabilidade 2024 confirma que a definição de metas de redução para os Escopos 1 e 2 (o objetivo) ainda é uma etapa futura planejada. Consequentemente, não é possível demonstrar progresso, nem possuir um plano de ação tático na instalação focado em atingir números que ainda não foram definidos.

Os dados de energia e emissões (Escopos 1, 2 e 3) apresentados publicamente não foram submetidos a auditoria externa ou atestação independente. Isso pode reduzir a aderência dos dados reportados perante os padrões mais exigentes do protocolo.

A empresa investe em projetos de sumidouro (reflorestamento), mas há lacuna quanto reportar esses dados conforme o rigor técnico exigido: não há o cálculo público da porcentagem de emissões compensadas nem detalhes sobre o credenciamento desses créditos. Além disso, não há evidência de uma transformação substancial do perfil energético alinhada a um compromisso de Net Zero, visto que tal compromisso de longo prazo ainda não foi assumido corporativamente.', '[]'),
    ('AGUA', 'AGUA-01', 1, 'Governança da Água', 'Confirmar se os compromissos e as responsabilidades estão estabelecidos e comunicados às Comunidades de Interesse (CDI) relevantes, com o propósito de apoiar a gestão sustentável da água.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', '[]'),
    ('AGUA', 'AGUA-02', 2, 'Gestão Operacional da Água', 'Confirmar se os planos e sistemas de gestão, associados à água, estão implementados no nível da  instalação. Este indicador inclui dois elementos: qualidade de água e quantidade de água.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, o balanço hídrico do empreendimento, plano de respostas, contigência e emergência de riscos e acidentes relacionados à água.

Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', '[]'),
    ('AGUA', 'AGUA-03', 3, 'Planejamento em Escala de Bacia Hidrográfica', 'Confirmar se a instalação apoia o envolvimento com outros usuários da água e com a CDI da bacia hidrográfica, além de participar do planejamento em escala de bacia hidrográfica e em fóruns de governança (quando existirem). Este indicador foca no planejamento de bacias hidrográficas, para além da pegada operacional da instalação.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, a participação da equipe do empreendedor em fóruns técnicos ou governança da bacia em questão.', '[]'),
    ('AGUA', 'AGUA-04', 4, 'Desempenho e Relatórios sobre a Água', 'Confirmar se foram estabelecidos objetivos ou metas, associados à água, para mensurar o desempenho e se existem relatórios para informar e subsidiar a tomada de decisões e comunicar o desempenho publicamente.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AA | Lacunas identificadas: Não foi evidenciada, através dos documentos e entrevistas, a busca ativa por feedback da CDI sobre o relatórios de água.', '[]'),
    ('BIODIV', 'BIODIV-01', 1, 'Compromisso em Conservação, Responsabilidade e Comunicação relacionado à da Biodiversidade', 'Confirmar se o compromisso e as responsabilidades corporativo estão vigentes, e se foram comunicadas aos funcionários responsáveis por apoiar a gestão de conservação da biodiversidade.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Não foi evidenciada uma política onde exista o comprometimento explicito a atingir perda líquida zero ou ganho líquido de biodiversidade.

Foi identificado como lacuna, a ausência de uma auditoria externa sobre os processos de gestão da biodiversidade.

Os relatórios de campo mostram que a empresa fala com a comunidade sobre renda, saúde e educação. Falta evidenciar que o tema "Conservação da Biodiversidade" também é pauta dessas reuniões comunitárias (CDI).', '[]'),
    ('BIODIV', 'BIODIV-02', 2, 'Planejamento e Implementação em Conservação da Biodiversidade na Instalação', 'Confirmar se foram implementados planos e sistemas de gestão efetivos na instalação, a fim de gerenciar os aspectos significativos da biodiversidade.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: O sistema de gestão da biodiversidade, embora operante, não foi submetido a auditorias independentes (externas) ou verificações internas dedicadas para atestar a eficácia das medidas de conservação e a precisão dos dados reportados.

A gestão ainda não incorporou os seguintes mecanismos de sustentabilidade:

- Não foi identificado a metodologia de valoração econômica de serviços ecossistêmicos integrada à tomada de decisão.
- Não foi identificado programas estruturados de voluntariado corporativo focados em biodiversidade.
- A empresa não produziu ou compartilha documentos orientativos (guias/manuais técnicos) para o setor ou para a região.
- Nos dados avaliados e consulta publica, não foram identificados registros de reconhecimento externo pelas práticas de conservação adotadas.', '[]'),
    ('BIODIV', 'BIODIV-03', 3, 'Relatórios em Conservação da Biodiversidade', 'Comprovar se a elaboração de relatórios está apta a informar os tomadores de decisão e comunicar o desempenho da empresa publicamente. Os relatórios de conservação da biodiversidade incluem elementos como políticas, monitoramento e iniciativas em conservação.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Não foi identificado evidência de que o o Relatório de Sustentabilidade tenha sido submetido a auditoria externa ou revisão independente para validar a precisão dos dados de biodiversidade divulgados.

Embora a instalação realize consultas para coleta de dados nas Comunidades de Interesse, não há evidência de que os relatórios finais de conservação tenham sido apresentados de volta a essas comunidades para coleta de feedback, nem que tal feedback tenha sido divulgado publicamente. O engajamento atual foca no diagnóstico, e não na validação do reporte.', '[]'),
    ('CRISE', 'CRISE-01', 1, 'Preparação da Gestão e Comunicações de Crise (Instalação)', '', '', '[]'),
    ('CRISE', 'CRISE-02', 2, 'Revisão', 'As empresas associadas irão revisar e atualizar o plano de gestão e comunicações de crise para assegurar-se que o documento continua pronto para responder às necessidades da empresa e suas operações, refletindo adequadamente os riscos associados às suas operações e às melhores práticas do setor.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão', '[]'),
    ('CRISE', 'CRISE-03', 3, 'Treinamento', 'Será realizado anualmente um treinamento em gestão de crise, incluindo exercícios de simulação de crise apropriados.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão', '[]'),
    ('DIVERSO', 'DIVERSO-01', 1, 'Liderança e estratégia', 'Confirmar que o escritório corporativo vem se engajando para desenvolver uma estratégia corporativa para locais de trabalho diversos, equitativos e inclusivos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Como lacuna observou-se que a instalação não atinge os níveis em transparência de dados sensíveis e auditoria cultural. Não há evidência de que os trabalhadores recebam atualizações detalhadas sobre as estatísticas e tipologias das denúncias recebidas (feedback do canal para a base), nem há relatórios públicos externos detalhando esses incidentes. Além disso, ainda não foi estabelecida uma rotina de revisão independente (auditoria externa a cada três anos) da cultura do local de trabalho ou da competência inclusiva da liderança, o que impede a validação externa da eficácia da estratégia implementada.', '[]'),
    ('DIVERSO', 'DIVERSO-02', 2, 'Promover a equidade, a diversidade e a inclusão', 'Confirmar que foram estabelecidos processos eficazes para promover uma cultura de equidade, diversidade e inclusão no local de trabalho e que o envolvimento ocorre com grupos e indivíduos relevantes, desde o desenvolvimento do processo até à avaliação.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AA | Lacunas identificadas: Como lacuna, não foi identificado que  o sistema de gestão ainda realizou o ciclo de avaliação de eficácia trienal dos critérios de diversidade com a participação de grupos representativos e divulgação pública dos resultados, o que limita a verificação de impacto a longo prazo. Além disso, embora haja conscientização dos fornecedores, os princípios de equidade, diversidade e inclusão ainda não estão formalmente integrados como critérios de decisão nos processos de aquisição e seleção técnica de contratados.', '[]'),
    ('DIVERSO', 'DIVERSO-03', 3, 'Monitoramento, desempenho e relatórios', 'Confirmar que a instalação se compromete a desenvolver uma abordagem visando o recolhimento de informações e a elaboração de relatórios sobre locais de trabalho diversos, equitativos e inclusivos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AAA', '[]'),
    ('SEGURO', 'SEGURO-01', 1, 'Compromisso e Responsabilidade para Gestão de Rejeitos', 'Confirmar que a instalação estabeleceu claramente a responsabilidade pela gestão e desempenho de segurança, saúde e respeito no local de trabalho, e que os compromissos de segurança, saúde e respeito no local de trabalho foram estabelecidos e comunicados de forma clara  aos empregados, empreiteiros e fornecedores.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AA | Lacunas identificadas: A lacuna identificada é a falta de auditoria externa. A empresa tem as regras e há evidência que todos as seguem, mas falta o relatório de um auditor externo, que ateste a aplicação dos compromissos e responsabilidades.', '[]'),
    ('SEGURO', 'SEGURO-02', 2, 'Sistemas de Gestão de Segurança e Saúde', 'Confirmar se foram estabelecidos os processos para planejar e gerenciar, de forma efetiva, os controles de saúde e  segurança, para prevenir a ocorrência de acidentes. Este indicador reconhece que a segurança e a saúde são uma responsabilidade compartilhada, e que a identificação de perigos, a avaliação de riscos e o estabelecimento de controles eficazes são parte integrante de um sistema de gestão eficaz. Embora esse indicador se concentre principalmente na segurança física e na saúde, alguns requisitos também se referem à saúde e à segurança psicológica.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: O protocolo exige um programa técnico (medição de ruído, poeira, sílica) gerido por um Higienista Qualificado. Não há evidência desse profissional ou relatório de evidência.

Não foi identificado evidencia de busca metodologias específicas para análise de risco e para prevenir fatalidades. Não há evidência de que a empresa já tenha implementado esse nível detalhado na gestão de riscos.

Não foi identificada evidência de auditorias externas que atestem a aderência aos protocolos.', '[]'),
    ('SEGURO', 'SEGURO-03', 3, 'Segurança Psicológica e Comportamento Respeitoso', 'Confirmar que a instalação implementa processos e programas para promover a segurança psicológica e o comportamento respeitoso no local de trabalho.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AA | Lacunas identificadas: A empresa atende aos principais requisitos. A locuna identificada trata auditoria. O protocolo exige não apenas uma revisão de documentos, mas uma auditoria que "envolva uma seção transversal de perspectivas... incluindo grupos subrepresentados". Ou seja, a empresa precisa provar que entrevistou mulheres, minorias raciais e locais de forma protegida para saber se eles se sentem seguros, e publicar esses resultados. Essas evidências não foram identificadas.', '[]'),
    ('SEGURO', 'SEGURO-04', 4, 'Treinamento, Comportamento e Cultura', 'Confirmar que foram estabelecidos processos para capacitar, de forma eficaz, empregados e empreiteiros sobre locais de trabalho seguros, saudáveis e respeitosos. O objetivo desse indicador é garantir a competência dos empregados e empreiteiros em identificar perigos e prevenir acidentes e que eles entendam a segurança, a saúde e o respeito como uma responsabilidade compartilhada e parte integrante do controle de riscos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Embora exista uma política contra assédio, não foi identificada evidencia de um programa de treinamento técnico que capacite os trabalhadores a identificar proativamente perigos psicossociais e avaliar esses riscos antes que se tornem incidentes. O foco atual é na denúncia e não na prevenção.

Não foram identificados processos formais para avaliar a competência de novos empregados após o treinamento (verificação de aprendizado) ou para monitorar a efetividade global dos programas de treinamento (se eles realmente mudaram o comportamento).

Não há evidências de que o design das instalações priorize acessibilidade e segurança psicológica (além do padrão legal), nem de que o sistema de compensação variável da liderança esteja matematicamente atrelado a indicadores de desempenho em saúde e segurança.', '[]'),
    ('SEGURO', 'SEGURO-05', 5, 'Monitoramento e Reporte', 'Confirmar se o desempenho em  segurança física e psicológica e da saúde é regularmente monitorado e reportado internamente e externamente.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: O sistema apresenta lacunas técnicas que impedem a conformidade com os níveis mais altos. O monitoramento atual é predominantemente reativo, carecendo de um Programa de Higiene Ocupacional estruturado para o controle de agentes nocivos (como ruído, poeira e calor) e de uma gestão focada em Controles Críticos para riscos de alta consequência. A integridade do sistema também carece de validação, uma vez que não foram observados evidencias de programas de auditoria voltados para a conformidade sistêmica, tampouco auditorias externas independentes para assegurar a precisão dos dados reportados. Por fim, não há um processo formalizado para avaliar a qualidade técnica das investigações de incidentes, limitando o potencial de aprendizado e prevenção de recorrências.', '[]'),
    ('SEGURO', 'SEGURO-06', 6, 'Desempenho em Segurança Física e Saúde', 'Reconhecer que dano zero é a meta final para todas as instalações. O objetivo deste indicador é confirmar que as metas de melhoria contínua para segurança física e saúde foram estabelecidas em cada instalação e que seu desempenho é avaliado. Se uma instalação tiver sofrido uma fatalidade no ano de referência, ela não é elegível para se qualificar ao Nível A ou outro nível superior.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): AA | Lacunas identificadas: Como lacuna foi observado que  a organização ainda não atinge os critérios máximos devido a dois fatores principais: a ausência de um histórico operacional de longo prazo que comprove a consistência da melhoria contínua, dada a fase recente do empreendimento, e a falta de uma auditoria externa independente que valide a precisão e confiabilidade dos dados de segurança reportados.', '[]'),
    ('TRABINF', 'TRABINF-01', 1, 'Prevenção ao Trabalho Forçado ou Análago ao Escravo', 'As empresas associadas têm processos implementados que são proporcionais ao risco jurisdicional para garantir que a não utilização do trabalho forçado ou análogo ao escravo.', '', '[]'),
    ('TRABINF', 'TRABINF-02', 2, 'Prevenção ao Trabalho Infantil', 'As empresas associadas têm processos implementados que são proporcionais aos riscos jurisdicionais para garantir que nenhuma criança menor de 18 anos esteja envolvida em trabalho que, pela natureza ou circunstâncias em que for executado, possa prejudicar a saúde, a segurança e a moral dos jovens, conforme definido em leis 
ou regulamentações nacionais e, finalmente, que nenhuma criança com idade inferior a 16 anos seja empregada, exceto se na condição de aprendiz e, mesmo assim, a partir de 14 anos e na forma da lei.', '', '[]'),
    ('COMUNIDADE', 'COMUNIDADE-01', 1, 'Identificação da Comunidade de Interesse (CDI)', 'Confirmar se processos estão implementados para identificar a CDI (incluindo comunidades e organizações indígenas, quilombolas e tradicionais) afetadas, ou consideradas afetadas pelas operações e atividades da empresa, ou que tenham algum interesse genuíno no desempenho e atividades da empresa e/ou operação. Os processos devem garantir que a identificação das comunidades de interesse seja reconsiderada, periodicamente, ao longo da vida útil da instalação.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Não foi identificada evidências de revisões periódicas do sistema e de que a instalação convide a comunidade para co-definir ou validar os critérios de identificação e mapeamento, mantendo o processo como uma iniciativa liderada exclusivamente pela empresa.', '[]'),
    ('COMUNIDADE', 'COMUNIDADE-02', 2, 'Engajamento Efetivo com a CDI e Diálogo', 'Confirmar se processos foram estabelecidos para apoiar o desenvolvimento e a manutenção de relações significativas com a CDI (incluindo comunidades e organizações indígenas e quilombolas), visando obter entendimento mútuo dos pontos de vista, construir relações efetivas e criar valores compartilhados e benefícios mútuos.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: A lacuna identifica é que  o modelo ainda é liderado pela empresa. A principal lacuna para os níveis avançados é a ausência de governança compartilhada: não há evidências de co-criação dos processos de diálogo com a comunidade, nem de mecanismos institucionalizados para tomada de decisão conjunta (poder deliberativo) sobre os projetos.', '[]'),
    ('COMUNIDADE', 'COMUNIDADE-03', 3, 'Engajamento e Diálogo Efetivo com Indígenas, Quilombolas', 'Confirmar se a instalação de mineração está construindo relações significativas e implementando processos reais de engajamento e tomada de decisão conjunta com comunidades indígenas e quilombolas.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): B | Lacunas identificadas: Os itens referentes à colaboração econômica direta, co-design de processos, acordos de benefícios mútuos e gestão compartilhada foram avaliados como Não Aplicáveis (N/A). Esta classificação baseia-se nos estudos socioambientais (EIA/RIMA e Relatório AIDH), que confirmam a ausência de comunidades indígenas ou quilombolas vivendo na Área de Influência Direta (AID) imediata da mina. Devido à inexistência de impacto direto de deslocamento ou interferência no modo de vida diário dessas comunidades, não se aplicam os requisitos operacionais para estabelecimento de cotas de emprego específicas, programas de negócios dedicados ou conselhos de monitoramento conjunto, sendo o relacionamento gerido na esfera institucional e de proteção de direitos.', '[]'),
    ('COMUNIDADE', 'COMUNIDADE-04', 4, 'Gestão de Benefícios e Impactos na Comunidade', 'Confirmar a implementação de processos para identificar e mitigar impactos comunitários (incluindo direitos humanos) e maximizar benefícios sociais. O indicador também valida o engajamento com a CDI sobre riscos críticos, como gestão de rejeitos, saúde e segurança da comunidade', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Como lacuna, não ficou evidenciado que o  modelo de gestão incorpora a tomada de decisão colaborativa (Governança Compartilhada), requisito essencial para os níveis de excelência. Embora a comunidade seja ouvida na priorização, as decisões finais sobre estratégias de mitigação, direcionamento de investimentos sociais e avaliação de eficácia permanecem centralizadas na empresa. Além disso, faltam processos de parceria para a gestão do legado e preparação da comunidade para a autonomia no período pós-fechamento.', '[]'),
    ('COMUNIDADE', 'COMUNIDADE-05', 5, 'Mecanismo de Resposta da CDI', 'Confirmar se existem processos implementados para receber, rastrear e responder a acidentes, questões preocupantes e prover feedback à CDI (incluindo as comunidades indígenas e quilombolas e organizações) levando a relações mais fortes e construindo a confiança.', 'Nivel de maturidade declarado (auditoria HIDROBR, doc. HBR101550001-GMN-RT001 Rev.1): A | Lacunas identificadas: Foi identificado que o sistema apresenta lacunas nos requisitos de engajamento avançado. O mecanismo foi desenvolvido  sem evidência de design colaborativo com a CDI afetada. Adicionalmente, o processo encerra-se na entrega da resposta, não sendo identificado um fluxo formal de follow-up com os usuários para verificar a satisfação final, nem uma revisão estruturada da eficácia global do sistema que tenha gerado ações corretivas baseadas na percepção da comunidade.', '[]')
  ) as v(topic_code, code, disp, title, descr, guidance, subreqs)
  join new_topics nt on nt.code = v.topic_code
  returning id, code
)
select count(*) as n_topics_ignore_placeholder from new_reqs;
commit;