-- ============================================================
-- IMPORTACAO: avaliacao TSM da GMining/Brazauro (Tocantinzinho)
-- a partir dos 9 arquivos HBR101550001-GMN-RT001_R1_APENDICE_II_TSM_*.xlsx
-- Pre-requisito: catalog_tsm.sql ja executado (34 requisitos em standard_requirements, standard_id=2)
-- Metodologia: aderencia por indicador calculada por barragem a partir dos criterios
-- (media dos valores 'Aderencia' por criterio nas planilhas '4/5/6... INDICADOR N'),
-- convertida para os 4 niveis do app por faixa (definido com o cliente em 2026-07-10):
--   >= 90%  -> Totalmente Conforme (100)
--   >= 75%  -> Conforme (75)
--   >= 50%  -> Parcialmente Conforme (50)
--   <  50%  -> Nao Conforme (0)
-- O nivel de maturidade declarado (C/B/A/AA/AAA) por indicador (aba '2. NIVEL DE
-- DESEMPENHO') e o mesmo para as 3 barragens (o arquivo nao o discrimina por estrutura).
begin;
with assessor as (
  select id as assessed_by from profiles where role in ('hidrobr_admin','hidrobr_consultant') order by created_at limit 1
),
raw(facility_id, requirement_code, status, score, score_value, assessment_text, maturity_level) as (
  values
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'REJ-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 94.4%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi identificado Sistema de Gestão de Disposição de Rejeitos (SGDR) formalmente estabelecido e implementado para nenhuma das estruturas avaliadas, em conformidade com as diretrizes e requisitos definidos no Guia de Gestão de Rejeitos do TSM.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'REJ-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 94.4%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi identificado Sistema de Gestão de Disposição de Rejeitos (SGDR) formalmente estabelecido e implementado para nenhuma das estruturas avaliadas, em conformidade com as diretrizes e requisitos definidos no Guia de Gestão de Rejeitos do TSM.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'REJ-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 94.4%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi identificado Sistema de Gestão de Disposição de Rejeitos (SGDR) formalmente estabelecido e implementado para nenhuma das estruturas avaliadas, em conformidade com as diretrizes e requisitos definidos no Guia de Gestão de Rejeitos do TSM.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'REJ-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 56.9%. Nivel de maturidade declarado: C. Lacunas identificadas: Além da ausência de um SGDR aderente ao Guia de Gestão de Rejeitos do TSM para todas as estruturas, verificou-se que a Célula 02, atualmente em fase de construção, não possui Plano de Ação de Emergência para Barragens (PAEBM) nem Plano de Gestão de Riscos de Barragens de Mineração (PGRBM) formalizados e documentados.', 'C'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'REJ-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 56.9%. Nivel de maturidade declarado: C. Lacunas identificadas: Além da ausência de um SGDR aderente ao Guia de Gestão de Rejeitos do TSM para todas as estruturas, verificou-se que a Célula 02, atualmente em fase de construção, não possui Plano de Ação de Emergência para Barragens (PAEBM) nem Plano de Gestão de Riscos de Barragens de Mineração (PGRBM) formalizados e documentados.', 'C'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'REJ-02', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 11.8%. Nivel de maturidade declarado: C. Lacunas identificadas: Além da ausência de um SGDR aderente ao Guia de Gestão de Rejeitos do TSM para todas as estruturas, verificou-se que a Célula 02, atualmente em fase de construção, não possui Plano de Ação de Emergência para Barragens (PAEBM) nem Plano de Gestão de Riscos de Barragens de Mineração (PGRBM) formalizados e documentados.', 'C'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'REJ-03', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Para a Célula 02, não foram identificados responsáveis formalmente designados e documentados para a gestão da estrutura. No caso das Barragens Tocantinzinho e Célula 01, embora existam responsáveis indicados, não foram identificados registros documentais que descrevam de forma completa, clara e estruturada as atribuições, responsabilidades e níveis de autoridade de todos os envolvidos.', 'C'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'REJ-03', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Para a Célula 02, não foram identificados responsáveis formalmente designados e documentados para a gestão da estrutura. No caso das Barragens Tocantinzinho e Célula 01, embora existam responsáveis indicados, não foram identificados registros documentais que descrevam de forma completa, clara e estruturada as atribuições, responsabilidades e níveis de autoridade de todos os envolvidos.', 'C'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'REJ-03', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 0.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Para a Célula 02, não foram identificados responsáveis formalmente designados e documentados para a gestão da estrutura. No caso das Barragens Tocantinzinho e Célula 01, embora existam responsáveis indicados, não foram identificados registros documentais que descrevam de forma completa, clara e estruturada as atribuições, responsabilidades e níveis de autoridade de todos os envolvidos.', 'C'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'REJ-04', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 0.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Não foram identificadas revisões anuais da gestão de rejeitos formalizadas e documentadas para nenhuma das três estruturas, conduzidas em conformidade com as diretrizes, escopo e conteúdo mínimo estabelecidos no Guia de Gestão de Rejeitos referenciado pelo TSM.', 'C'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'REJ-04', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 0.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Não foram identificadas revisões anuais da gestão de rejeitos formalizadas e documentadas para nenhuma das três estruturas, conduzidas em conformidade com as diretrizes, escopo e conteúdo mínimo estabelecidos no Guia de Gestão de Rejeitos referenciado pelo TSM.', 'C'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'REJ-04', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 0.0%. Nivel de maturidade declarado: C. Lacunas identificadas: Não foram identificadas revisões anuais da gestão de rejeitos formalizadas e documentadas para nenhuma das três estruturas, conduzidas em conformidade com as diretrizes, escopo e conteúdo mínimo estabelecidos no Guia de Gestão de Rejeitos referenciado pelo TSM.', 'C'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'REJ-05', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 40.6%. Nivel de maturidade declarado: C. Lacunas identificadas: A Célula 02 não possui Manual de Operação, Manutenção e Monitoramento (OMS) elaborado. Adicionalmente, os manuais existentes para as Barragens Tocantinzinho e Célula 01 não atendem integralmente ao conteúdo, à abrangência e aos requisitos previstos no Guia de OMS referenciado pelo TSM, demandando adequações.', 'C'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'REJ-05', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 41.0%. Nivel de maturidade declarado: C. Lacunas identificadas: A Célula 02 não possui Manual de Operação, Manutenção e Monitoramento (OMS) elaborado. Adicionalmente, os manuais existentes para as Barragens Tocantinzinho e Célula 01 não atendem integralmente ao conteúdo, à abrangência e aos requisitos previstos no Guia de OMS referenciado pelo TSM, demandando adequações.', 'C'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'REJ-05', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 0.0%. Nivel de maturidade declarado: C. Lacunas identificadas: A Célula 02 não possui Manual de Operação, Manutenção e Monitoramento (OMS) elaborado. Adicionalmente, os manuais existentes para as Barragens Tocantinzinho e Célula 01 não atendem integralmente ao conteúdo, à abrangência e aos requisitos previstos no Guia de OMS referenciado pelo TSM, demandando adequações.', 'C'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CLIMA-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 61.3%. Nivel de maturidade declarado: B. Lacunas identificadas: Existem lacunas quantitativas para o futuro. O último relatório admite que a meta de redução de emissões para 2030 ainda é uma atividade futura, e não há um compromisso formalizado de "Net Zero" para 2050. Também não foram encontradas evidências de mecanismos financeiros avançados, como o uso de um preço interno de carbono para avaliar investimentos. Na cadeia de valor, embora o diálogo com fornecedores tenha começado, ainda não há critérios climáticos consolidados para compras e seleção de parceiros. Por fim, não há registros de atuação direta junto ao Governo Federal para a definição de planos setoriais de mitigação.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CLIMA-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 61.3%. Nivel de maturidade declarado: B. Lacunas identificadas: Existem lacunas quantitativas para o futuro. O último relatório admite que a meta de redução de emissões para 2030 ainda é uma atividade futura, e não há um compromisso formalizado de "Net Zero" para 2050. Também não foram encontradas evidências de mecanismos financeiros avançados, como o uso de um preço interno de carbono para avaliar investimentos. Na cadeia de valor, embora o diálogo com fornecedores tenha começado, ainda não há critérios climáticos consolidados para compras e seleção de parceiros. Por fim, não há registros de atuação direta junto ao Governo Federal para a definição de planos setoriais de mitigação.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CLIMA-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 61.3%. Nivel de maturidade declarado: B. Lacunas identificadas: Existem lacunas quantitativas para o futuro. O último relatório admite que a meta de redução de emissões para 2030 ainda é uma atividade futura, e não há um compromisso formalizado de "Net Zero" para 2050. Também não foram encontradas evidências de mecanismos financeiros avançados, como o uso de um preço interno de carbono para avaliar investimentos. Na cadeia de valor, embora o diálogo com fornecedores tenha começado, ainda não há critérios climáticos consolidados para compras e seleção de parceiros. Por fim, não há registros de atuação direta junto ao Governo Federal para a definição de planos setoriais de mitigação.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CLIMA-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão de energia e emissões de GEE carece de um mecanismo robusto de verificação independente. Os documentos confirmam que os dados e processos de gestão não foram submetidos a uma auditoria externa. Além disso, não há evidência de que tenha sido realizada uma auditoria interna dedicada especificamente para validar a eficácia e conformidade deste sistema de gestão, o que limita a garantia de integridade dos controles climáticos reportados.

A aplicação do sistema de gestão permanece restrita às operações internas da instalação. Não foram encontrados mecanismos que estendam as diretrizes, metas e monitoramento de energia e GEE para todo o ciclo de vida das atividades, abrangendo fornecedores, clientes e terceiros. Embora a empresa tenha iniciado o mapeamento de emissões indiretas, as práticas de gestão e exigências contratuais climáticas ainda não são aplicadas à cadeia de suprimentos.

A gestão de riscos físicos e adaptação baseia-se estritamente em critérios técnicos e de engenharia, sem incorporar o conhecimento comunitário, cultural ou tradicional local nas avaliações de impacto climático ou no desenho das medidas de adaptação. Adicionalmente, não há registros de colaboração ou parcerias ativas com as Comunidades de Interesse (CDI) ou outras organizações externas voltadas especificamente para a gestão conjunta de impactos climáticos físicos e estratégias de adaptação compartilhada no território.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CLIMA-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão de energia e emissões de GEE carece de um mecanismo robusto de verificação independente. Os documentos confirmam que os dados e processos de gestão não foram submetidos a uma auditoria externa. Além disso, não há evidência de que tenha sido realizada uma auditoria interna dedicada especificamente para validar a eficácia e conformidade deste sistema de gestão, o que limita a garantia de integridade dos controles climáticos reportados.

A aplicação do sistema de gestão permanece restrita às operações internas da instalação. Não foram encontrados mecanismos que estendam as diretrizes, metas e monitoramento de energia e GEE para todo o ciclo de vida das atividades, abrangendo fornecedores, clientes e terceiros. Embora a empresa tenha iniciado o mapeamento de emissões indiretas, as práticas de gestão e exigências contratuais climáticas ainda não são aplicadas à cadeia de suprimentos.

A gestão de riscos físicos e adaptação baseia-se estritamente em critérios técnicos e de engenharia, sem incorporar o conhecimento comunitário, cultural ou tradicional local nas avaliações de impacto climático ou no desenho das medidas de adaptação. Adicionalmente, não há registros de colaboração ou parcerias ativas com as Comunidades de Interesse (CDI) ou outras organizações externas voltadas especificamente para a gestão conjunta de impactos climáticos físicos e estratégias de adaptação compartilhada no território.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CLIMA-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão de energia e emissões de GEE carece de um mecanismo robusto de verificação independente. Os documentos confirmam que os dados e processos de gestão não foram submetidos a uma auditoria externa. Além disso, não há evidência de que tenha sido realizada uma auditoria interna dedicada especificamente para validar a eficácia e conformidade deste sistema de gestão, o que limita a garantia de integridade dos controles climáticos reportados.

A aplicação do sistema de gestão permanece restrita às operações internas da instalação. Não foram encontrados mecanismos que estendam as diretrizes, metas e monitoramento de energia e GEE para todo o ciclo de vida das atividades, abrangendo fornecedores, clientes e terceiros. Embora a empresa tenha iniciado o mapeamento de emissões indiretas, as práticas de gestão e exigências contratuais climáticas ainda não são aplicadas à cadeia de suprimentos.

A gestão de riscos físicos e adaptação baseia-se estritamente em critérios técnicos e de engenharia, sem incorporar o conhecimento comunitário, cultural ou tradicional local nas avaliações de impacto climático ou no desenho das medidas de adaptação. Adicionalmente, não há registros de colaboração ou parcerias ativas com as Comunidades de Interesse (CDI) ou outras organizações externas voltadas especificamente para a gestão conjunta de impactos climáticos físicos e estratégias de adaptação compartilhada no território.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CLIMA-03', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 35.3%. Nivel de maturidade declarado: C. Lacunas identificadas: Embora o empreendedor tenha realizado o inventário (o diagnóstico), o Relatório de Sustentabilidade 2024 confirma que a definição de metas de redução para os Escopos 1 e 2 (o objetivo) ainda é uma etapa futura planejada. Consequentemente, não é possível demonstrar progresso, nem possuir um plano de ação tático na instalação focado em atingir números que ainda não foram definidos.

Os dados de energia e emissões (Escopos 1, 2 e 3) apresentados publicamente não foram submetidos a auditoria externa ou atestação independente. Isso pode reduzir a aderência dos dados reportados perante os padrões mais exigentes do protocolo.

A empresa investe em projetos de sumidouro (reflorestamento), mas há lacuna quanto reportar esses dados conforme o rigor técnico exigido: não há o cálculo público da porcentagem de emissões compensadas nem detalhes sobre o credenciamento desses créditos. Além disso, não há evidência de uma transformação substancial do perfil energético alinhada a um compromisso de Net Zero, visto que tal compromisso de longo prazo ainda não foi assumido corporativamente.', 'C'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CLIMA-03', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 35.3%. Nivel de maturidade declarado: C. Lacunas identificadas: Embora o empreendedor tenha realizado o inventário (o diagnóstico), o Relatório de Sustentabilidade 2024 confirma que a definição de metas de redução para os Escopos 1 e 2 (o objetivo) ainda é uma etapa futura planejada. Consequentemente, não é possível demonstrar progresso, nem possuir um plano de ação tático na instalação focado em atingir números que ainda não foram definidos.

Os dados de energia e emissões (Escopos 1, 2 e 3) apresentados publicamente não foram submetidos a auditoria externa ou atestação independente. Isso pode reduzir a aderência dos dados reportados perante os padrões mais exigentes do protocolo.

A empresa investe em projetos de sumidouro (reflorestamento), mas há lacuna quanto reportar esses dados conforme o rigor técnico exigido: não há o cálculo público da porcentagem de emissões compensadas nem detalhes sobre o credenciamento desses créditos. Além disso, não há evidência de uma transformação substancial do perfil energético alinhada a um compromisso de Net Zero, visto que tal compromisso de longo prazo ainda não foi assumido corporativamente.', 'C'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CLIMA-03', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 35.3%. Nivel de maturidade declarado: C. Lacunas identificadas: Embora o empreendedor tenha realizado o inventário (o diagnóstico), o Relatório de Sustentabilidade 2024 confirma que a definição de metas de redução para os Escopos 1 e 2 (o objetivo) ainda é uma etapa futura planejada. Consequentemente, não é possível demonstrar progresso, nem possuir um plano de ação tático na instalação focado em atingir números que ainda não foram definidos.

Os dados de energia e emissões (Escopos 1, 2 e 3) apresentados publicamente não foram submetidos a auditoria externa ou atestação independente. Isso pode reduzir a aderência dos dados reportados perante os padrões mais exigentes do protocolo.

A empresa investe em projetos de sumidouro (reflorestamento), mas há lacuna quanto reportar esses dados conforme o rigor técnico exigido: não há o cálculo público da porcentagem de emissões compensadas nem detalhes sobre o credenciamento desses créditos. Além disso, não há evidência de uma transformação substancial do perfil energético alinhada a um compromisso de Net Zero, visto que tal compromisso de longo prazo ainda não foi assumido corporativamente.', 'C'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'AGUA-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 92.3%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'AGUA-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 92.3%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'AGUA-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 92.3%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'AGUA-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 54.5%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, o balanço hídrico do empreendimento, plano de respostas, contigência e emergência de riscos e acidentes relacionados à água.

Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'AGUA-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, o balanço hídrico do empreendimento, plano de respostas, contigência e emergência de riscos e acidentes relacionados à água.

Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'AGUA-02', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: 47.6%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, o balanço hídrico do empreendimento, plano de respostas, contigência e emergência de riscos e acidentes relacionados à água.

Não foi evidenciado, através dos documentos e entrevistas, processos que visam identificar as oportunidades de melhoria no desempenho da água associadas ao balanço hídrico do empreendimento.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'AGUA-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, a participação da equipe do empreendedor em fóruns técnicos ou governança da bacia em questão.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'AGUA-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, a participação da equipe do empreendedor em fóruns técnicos ou governança da bacia em questão.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'AGUA-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: B. Lacunas identificadas: Não foi evidenciado, através dos documentos e entrevistas, a participação da equipe do empreendedor em fóruns técnicos ou governança da bacia em questão.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'AGUA-04', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 87.5%. Nivel de maturidade declarado: AA. Lacunas identificadas: Não foi evidenciada, através dos documentos e entrevistas, a busca ativa por feedback da CDI sobre o relatórios de água.', 'AA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'AGUA-04', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 87.5%. Nivel de maturidade declarado: AA. Lacunas identificadas: Não foi evidenciada, através dos documentos e entrevistas, a busca ativa por feedback da CDI sobre o relatórios de água.', 'AA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'AGUA-04', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 87.5%. Nivel de maturidade declarado: AA. Lacunas identificadas: Não foi evidenciada, através dos documentos e entrevistas, a busca ativa por feedback da CDI sobre o relatórios de água.', 'AA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'BIODIV-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 77.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciada uma política onde exista o comprometimento explicito a atingir perda líquida zero ou ganho líquido de biodiversidade.

Foi identificado como lacuna, a ausência de uma auditoria externa sobre os processos de gestão da biodiversidade.

Os relatórios de campo mostram que a empresa fala com a comunidade sobre renda, saúde e educação. Falta evidenciar que o tema "Conservação da Biodiversidade" também é pauta dessas reuniões comunitárias (CDI).', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'BIODIV-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 77.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciada uma política onde exista o comprometimento explicito a atingir perda líquida zero ou ganho líquido de biodiversidade.

Foi identificado como lacuna, a ausência de uma auditoria externa sobre os processos de gestão da biodiversidade.

Os relatórios de campo mostram que a empresa fala com a comunidade sobre renda, saúde e educação. Falta evidenciar que o tema "Conservação da Biodiversidade" também é pauta dessas reuniões comunitárias (CDI).', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'BIODIV-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 77.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi evidenciada uma política onde exista o comprometimento explicito a atingir perda líquida zero ou ganho líquido de biodiversidade.

Foi identificado como lacuna, a ausência de uma auditoria externa sobre os processos de gestão da biodiversidade.

Os relatórios de campo mostram que a empresa fala com a comunidade sobre renda, saúde e educação. Falta evidenciar que o tema "Conservação da Biodiversidade" também é pauta dessas reuniões comunitárias (CDI).', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'BIODIV-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.6%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão da biodiversidade, embora operante, não foi submetido a auditorias independentes (externas) ou verificações internas dedicadas para atestar a eficácia das medidas de conservação e a precisão dos dados reportados.

A gestão ainda não incorporou os seguintes mecanismos de sustentabilidade:

- Não foi identificado a metodologia de valoração econômica de serviços ecossistêmicos integrada à tomada de decisão.
- Não foi identificado programas estruturados de voluntariado corporativo focados em biodiversidade.
- A empresa não produziu ou compartilha documentos orientativos (guias/manuais técnicos) para o setor ou para a região.
- Nos dados avaliados e consulta publica, não foram identificados registros de reconhecimento externo pelas práticas de conservação adotadas.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'BIODIV-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.6%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão da biodiversidade, embora operante, não foi submetido a auditorias independentes (externas) ou verificações internas dedicadas para atestar a eficácia das medidas de conservação e a precisão dos dados reportados.

A gestão ainda não incorporou os seguintes mecanismos de sustentabilidade:

- Não foi identificado a metodologia de valoração econômica de serviços ecossistêmicos integrada à tomada de decisão.
- Não foi identificado programas estruturados de voluntariado corporativo focados em biodiversidade.
- A empresa não produziu ou compartilha documentos orientativos (guias/manuais técnicos) para o setor ou para a região.
- Nos dados avaliados e consulta publica, não foram identificados registros de reconhecimento externo pelas práticas de conservação adotadas.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'BIODIV-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.6%. Nivel de maturidade declarado: A. Lacunas identificadas: O sistema de gestão da biodiversidade, embora operante, não foi submetido a auditorias independentes (externas) ou verificações internas dedicadas para atestar a eficácia das medidas de conservação e a precisão dos dados reportados.

A gestão ainda não incorporou os seguintes mecanismos de sustentabilidade:

- Não foi identificado a metodologia de valoração econômica de serviços ecossistêmicos integrada à tomada de decisão.
- Não foi identificado programas estruturados de voluntariado corporativo focados em biodiversidade.
- A empresa não produziu ou compartilha documentos orientativos (guias/manuais técnicos) para o setor ou para a região.
- Nos dados avaliados e consulta publica, não foram identificados registros de reconhecimento externo pelas práticas de conservação adotadas.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'BIODIV-03', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificado evidência de que o o Relatório de Sustentabilidade tenha sido submetido a auditoria externa ou revisão independente para validar a precisão dos dados de biodiversidade divulgados.

Embora a instalação realize consultas para coleta de dados nas Comunidades de Interesse, não há evidência de que os relatórios finais de conservação tenham sido apresentados de volta a essas comunidades para coleta de feedback, nem que tal feedback tenha sido divulgado publicamente. O engajamento atual foca no diagnóstico, e não na validação do reporte.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'BIODIV-03', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificado evidência de que o o Relatório de Sustentabilidade tenha sido submetido a auditoria externa ou revisão independente para validar a precisão dos dados de biodiversidade divulgados.

Embora a instalação realize consultas para coleta de dados nas Comunidades de Interesse, não há evidência de que os relatórios finais de conservação tenham sido apresentados de volta a essas comunidades para coleta de feedback, nem que tal feedback tenha sido divulgado publicamente. O engajamento atual foca no diagnóstico, e não na validação do reporte.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'BIODIV-03', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificado evidência de que o o Relatório de Sustentabilidade tenha sido submetido a auditoria externa ou revisão independente para validar a precisão dos dados de biodiversidade divulgados.

Embora a instalação realize consultas para coleta de dados nas Comunidades de Interesse, não há evidência de que os relatórios finais de conservação tenham sido apresentados de volta a essas comunidades para coleta de feedback, nem que tal feedback tenha sido divulgado publicamente. O engajamento atual foca no diagnóstico, e não na validação do reporte.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CRISE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: nao informado.', null),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CRISE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: nao informado.', null),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CRISE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: nao informado.', null),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CRISE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.1%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CRISE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.1%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CRISE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.1%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'CRISE-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 88.9%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'CRISE-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 88.9%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'CRISE-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 88.9%. Nivel de maturidade declarado: Como lacuna, não foi identificado equipe de gestão de crise corporativo, não sendo possível avaliar a atualização do plano de gestão em questão.', null),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'DIVERSO-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 60.9%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna observou-se que a instalação não atinge os níveis em transparência de dados sensíveis e auditoria cultural. Não há evidência de que os trabalhadores recebam atualizações detalhadas sobre as estatísticas e tipologias das denúncias recebidas (feedback do canal para a base), nem há relatórios públicos externos detalhando esses incidentes. Além disso, ainda não foi estabelecida uma rotina de revisão independente (auditoria externa a cada três anos) da cultura do local de trabalho ou da competência inclusiva da liderança, o que impede a validação externa da eficácia da estratégia implementada.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'DIVERSO-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 60.9%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna observou-se que a instalação não atinge os níveis em transparência de dados sensíveis e auditoria cultural. Não há evidência de que os trabalhadores recebam atualizações detalhadas sobre as estatísticas e tipologias das denúncias recebidas (feedback do canal para a base), nem há relatórios públicos externos detalhando esses incidentes. Além disso, ainda não foi estabelecida uma rotina de revisão independente (auditoria externa a cada três anos) da cultura do local de trabalho ou da competência inclusiva da liderança, o que impede a validação externa da eficácia da estratégia implementada.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'DIVERSO-01', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 60.9%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna observou-se que a instalação não atinge os níveis em transparência de dados sensíveis e auditoria cultural. Não há evidência de que os trabalhadores recebam atualizações detalhadas sobre as estatísticas e tipologias das denúncias recebidas (feedback do canal para a base), nem há relatórios públicos externos detalhando esses incidentes. Além disso, ainda não foi estabelecida uma rotina de revisão independente (auditoria externa a cada três anos) da cultura do local de trabalho ou da competência inclusiva da liderança, o que impede a validação externa da eficácia da estratégia implementada.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'DIVERSO-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.0%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna, não foi identificado que  o sistema de gestão ainda realizou o ciclo de avaliação de eficácia trienal dos critérios de diversidade com a participação de grupos representativos e divulgação pública dos resultados, o que limita a verificação de impacto a longo prazo. Além disso, embora haja conscientização dos fornecedores, os princípios de equidade, diversidade e inclusão ainda não estão formalmente integrados como critérios de decisão nos processos de aquisição e seleção técnica de contratados.', 'AA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'DIVERSO-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.0%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna, não foi identificado que  o sistema de gestão ainda realizou o ciclo de avaliação de eficácia trienal dos critérios de diversidade com a participação de grupos representativos e divulgação pública dos resultados, o que limita a verificação de impacto a longo prazo. Além disso, embora haja conscientização dos fornecedores, os princípios de equidade, diversidade e inclusão ainda não estão formalmente integrados como critérios de decisão nos processos de aquisição e seleção técnica de contratados.', 'AA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'DIVERSO-02', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 80.0%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna, não foi identificado que  o sistema de gestão ainda realizou o ciclo de avaliação de eficácia trienal dos critérios de diversidade com a participação de grupos representativos e divulgação pública dos resultados, o que limita a verificação de impacto a longo prazo. Além disso, embora haja conscientização dos fornecedores, os princípios de equidade, diversidade e inclusão ainda não estão formalmente integrados como critérios de decisão nos processos de aquisição e seleção técnica de contratados.', 'AA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'DIVERSO-03', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: AAA.', 'AAA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'DIVERSO-03', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: AAA.', 'AAA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'DIVERSO-03', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: AAA.', 'AAA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-01', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: sem dados. Nivel de maturidade declarado: AA. Lacunas identificadas: A lacuna identificada é a falta de auditoria externa. A empresa tem as regras e há evidência que todos as seguem, mas falta o relatório de um auditor externo, que ateste a aplicação dos compromissos e responsabilidades.', 'AA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-01', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: sem dados. Nivel de maturidade declarado: AA. Lacunas identificadas: A lacuna identificada é a falta de auditoria externa. A empresa tem as regras e há evidência que todos as seguem, mas falta o relatório de um auditor externo, que ateste a aplicação dos compromissos e responsabilidades.', 'AA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 75.0%. Nivel de maturidade declarado: AA. Lacunas identificadas: A lacuna identificada é a falta de auditoria externa. A empresa tem as regras e há evidência que todos as seguem, mas falta o relatório de um auditor externo, que ateste a aplicação dos compromissos e responsabilidades.', 'AA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: B. Lacunas identificadas: O protocolo exige um programa técnico (medição de ruído, poeira, sílica) gerido por um Higienista Qualificado. Não há evidência desse profissional ou relatório de evidência.

Não foi identificado evidencia de busca metodologias específicas para análise de risco e para prevenir fatalidades. Não há evidência de que a empresa já tenha implementado esse nível detalhado na gestão de riscos.

Não foi identificada evidência de auditorias externas que atestem a aderência aos protocolos.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: B. Lacunas identificadas: O protocolo exige um programa técnico (medição de ruído, poeira, sílica) gerido por um Higienista Qualificado. Não há evidência desse profissional ou relatório de evidência.

Não foi identificado evidencia de busca metodologias específicas para análise de risco e para prevenir fatalidades. Não há evidência de que a empresa já tenha implementado esse nível detalhado na gestão de riscos.

Não foi identificada evidência de auditorias externas que atestem a aderência aos protocolos.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 50.0%. Nivel de maturidade declarado: B. Lacunas identificadas: O protocolo exige um programa técnico (medição de ruído, poeira, sílica) gerido por um Higienista Qualificado. Não há evidência desse profissional ou relatório de evidência.

Não foi identificado evidencia de busca metodologias específicas para análise de risco e para prevenir fatalidades. Não há evidência de que a empresa já tenha implementado esse nível detalhado na gestão de riscos.

Não foi identificada evidência de auditorias externas que atestem a aderência aos protocolos.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 82.4%. Nivel de maturidade declarado: AA. Lacunas identificadas: A empresa atende aos principais requisitos. A locuna identificada trata auditoria. O protocolo exige não apenas uma revisão de documentos, mas uma auditoria que "envolva uma seção transversal de perspectivas... incluindo grupos subrepresentados". Ou seja, a empresa precisa provar que entrevistou mulheres, minorias raciais e locais de forma protegida para saber se eles se sentem seguros, e publicar esses resultados. Essas evidências não foram identificadas.', 'AA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 82.4%. Nivel de maturidade declarado: AA. Lacunas identificadas: A empresa atende aos principais requisitos. A locuna identificada trata auditoria. O protocolo exige não apenas uma revisão de documentos, mas uma auditoria que "envolva uma seção transversal de perspectivas... incluindo grupos subrepresentados". Ou seja, a empresa precisa provar que entrevistou mulheres, minorias raciais e locais de forma protegida para saber se eles se sentem seguros, e publicar esses resultados. Essas evidências não foram identificadas.', 'AA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-03', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 82.4%. Nivel de maturidade declarado: AA. Lacunas identificadas: A empresa atende aos principais requisitos. A locuna identificada trata auditoria. O protocolo exige não apenas uma revisão de documentos, mas uma auditoria que "envolva uma seção transversal de perspectivas... incluindo grupos subrepresentados". Ou seja, a empresa precisa provar que entrevistou mulheres, minorias raciais e locais de forma protegida para saber se eles se sentem seguros, e publicar esses resultados. Essas evidências não foram identificadas.', 'AA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 69.6%. Nivel de maturidade declarado: B. Lacunas identificadas: Embora exista uma política contra assédio, não foi identificada evidencia de um programa de treinamento técnico que capacite os trabalhadores a identificar proativamente perigos psicossociais e avaliar esses riscos antes que se tornem incidentes. O foco atual é na denúncia e não na prevenção.

Não foram identificados processos formais para avaliar a competência de novos empregados após o treinamento (verificação de aprendizado) ou para monitorar a efetividade global dos programas de treinamento (se eles realmente mudaram o comportamento).

Não há evidências de que o design das instalações priorize acessibilidade e segurança psicológica (além do padrão legal), nem de que o sistema de compensação variável da liderança esteja matematicamente atrelado a indicadores de desempenho em saúde e segurança.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 69.6%. Nivel de maturidade declarado: B. Lacunas identificadas: Embora exista uma política contra assédio, não foi identificada evidencia de um programa de treinamento técnico que capacite os trabalhadores a identificar proativamente perigos psicossociais e avaliar esses riscos antes que se tornem incidentes. O foco atual é na denúncia e não na prevenção.

Não foram identificados processos formais para avaliar a competência de novos empregados após o treinamento (verificação de aprendizado) ou para monitorar a efetividade global dos programas de treinamento (se eles realmente mudaram o comportamento).

Não há evidências de que o design das instalações priorize acessibilidade e segurança psicológica (além do padrão legal), nem de que o sistema de compensação variável da liderança esteja matematicamente atrelado a indicadores de desempenho em saúde e segurança.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 69.6%. Nivel de maturidade declarado: B. Lacunas identificadas: Embora exista uma política contra assédio, não foi identificada evidencia de um programa de treinamento técnico que capacite os trabalhadores a identificar proativamente perigos psicossociais e avaliar esses riscos antes que se tornem incidentes. O foco atual é na denúncia e não na prevenção.

Não foram identificados processos formais para avaliar a competência de novos empregados após o treinamento (verificação de aprendizado) ou para monitorar a efetividade global dos programas de treinamento (se eles realmente mudaram o comportamento).

Não há evidências de que o design das instalações priorize acessibilidade e segurança psicológica (além do padrão legal), nem de que o sistema de compensação variável da liderança esteja matematicamente atrelado a indicadores de desempenho em saúde e segurança.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.9%. Nivel de maturidade declarado: B. Lacunas identificadas: O sistema apresenta lacunas técnicas que impedem a conformidade com os níveis mais altos. O monitoramento atual é predominantemente reativo, carecendo de um Programa de Higiene Ocupacional estruturado para o controle de agentes nocivos (como ruído, poeira e calor) e de uma gestão focada em Controles Críticos para riscos de alta consequência. A integridade do sistema também carece de validação, uma vez que não foram observados evidencias de programas de auditoria voltados para a conformidade sistêmica, tampouco auditorias externas independentes para assegurar a precisão dos dados reportados. Por fim, não há um processo formalizado para avaliar a qualidade técnica das investigações de incidentes, limitando o potencial de aprendizado e prevenção de recorrências.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.9%. Nivel de maturidade declarado: B. Lacunas identificadas: O sistema apresenta lacunas técnicas que impedem a conformidade com os níveis mais altos. O monitoramento atual é predominantemente reativo, carecendo de um Programa de Higiene Ocupacional estruturado para o controle de agentes nocivos (como ruído, poeira e calor) e de uma gestão focada em Controles Críticos para riscos de alta consequência. A integridade do sistema também carece de validação, uma vez que não foram observados evidencias de programas de auditoria voltados para a conformidade sistêmica, tampouco auditorias externas independentes para assegurar a precisão dos dados reportados. Por fim, não há um processo formalizado para avaliar a qualidade técnica das investigações de incidentes, limitando o potencial de aprendizado e prevenção de recorrências.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 57.9%. Nivel de maturidade declarado: B. Lacunas identificadas: O sistema apresenta lacunas técnicas que impedem a conformidade com os níveis mais altos. O monitoramento atual é predominantemente reativo, carecendo de um Programa de Higiene Ocupacional estruturado para o controle de agentes nocivos (como ruído, poeira e calor) e de uma gestão focada em Controles Críticos para riscos de alta consequência. A integridade do sistema também carece de validação, uma vez que não foram observados evidencias de programas de auditoria voltados para a conformidade sistêmica, tampouco auditorias externas independentes para assegurar a precisão dos dados reportados. Por fim, não há um processo formalizado para avaliar a qualidade técnica das investigações de incidentes, limitando o potencial de aprendizado e prevenção de recorrências.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'SEGURO-06', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna foi observado que  a organização ainda não atinge os critérios máximos devido a dois fatores principais: a ausência de um histórico operacional de longo prazo que comprove a consistência da melhoria contínua, dada a fase recente do empreendimento, e a falta de uma auditoria externa independente que valide a precisão e confiabilidade dos dados de segurança reportados.', 'AA'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'SEGURO-06', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna foi observado que  a organização ainda não atinge os critérios máximos devido a dois fatores principais: a ausência de um histórico operacional de longo prazo que comprove a consistência da melhoria contínua, dada a fase recente do empreendimento, e a falta de uma auditoria externa independente que valide a precisão e confiabilidade dos dados de segurança reportados.', 'AA'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'SEGURO-06', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 83.3%. Nivel de maturidade declarado: AA. Lacunas identificadas: Como lacuna foi observado que  a organização ainda não atinge os critérios máximos devido a dois fatores principais: a ausência de um histórico operacional de longo prazo que comprove a consistência da melhoria contínua, dada a fase recente do empreendimento, e a falta de uma auditoria externa independente que valide a precisão e confiabilidade dos dados de segurança reportados.', 'AA'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'TRABINF-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'TRABINF-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'TRABINF-01', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'TRABINF-02', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'TRABINF-02', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'TRABINF-02', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: nao informado.', null),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'COMUNIDADE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificada evidências de revisões periódicas do sistema e de que a instalação convide a comunidade para co-definir ou validar os critérios de identificação e mapeamento, mantendo o processo como uma iniciativa liderada exclusivamente pela empresa.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'COMUNIDADE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificada evidências de revisões periódicas do sistema e de que a instalação convide a comunidade para co-definir ou validar os critérios de identificação e mapeamento, mantendo o processo como uma iniciativa liderada exclusivamente pela empresa.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'COMUNIDADE-01', 'approved'::requirement_status, 'conforming'::assessment_score, 75, 'Aderencia calculada: 81.8%. Nivel de maturidade declarado: A. Lacunas identificadas: Não foi identificada evidências de revisões periódicas do sistema e de que a instalação convide a comunidade para co-definir ou validar os critérios de identificação e mapeamento, mantendo o processo como uma iniciativa liderada exclusivamente pela empresa.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'COMUNIDADE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: B. Lacunas identificadas: A lacuna identifica é que  o modelo ainda é liderado pela empresa. A principal lacuna para os níveis avançados é a ausência de governança compartilhada: não há evidências de co-criação dos processos de diálogo com a comunidade, nem de mecanismos institucionalizados para tomada de decisão conjunta (poder deliberativo) sobre os projetos.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'COMUNIDADE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: B. Lacunas identificadas: A lacuna identifica é que  o modelo ainda é liderado pela empresa. A principal lacuna para os níveis avançados é a ausência de governança compartilhada: não há evidências de co-criação dos processos de diálogo com a comunidade, nem de mecanismos institucionalizados para tomada de decisão conjunta (poder deliberativo) sobre os projetos.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'COMUNIDADE-02', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 66.7%. Nivel de maturidade declarado: B. Lacunas identificadas: A lacuna identifica é que  o modelo ainda é liderado pela empresa. A principal lacuna para os níveis avançados é a ausência de governança compartilhada: não há evidências de co-criação dos processos de diálogo com a comunidade, nem de mecanismos institucionalizados para tomada de decisão conjunta (poder deliberativo) sobre os projetos.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'COMUNIDADE-03', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: B. Lacunas identificadas: Os itens referentes à colaboração econômica direta, co-design de processos, acordos de benefícios mútuos e gestão compartilhada foram avaliados como Não Aplicáveis (N/A). Esta classificação baseia-se nos estudos socioambientais (EIA/RIMA e Relatório AIDH), que confirmam a ausência de comunidades indígenas ou quilombolas vivendo na Área de Influência Direta (AID) imediata da mina. Devido à inexistência de impacto direto de deslocamento ou interferência no modo de vida diário dessas comunidades, não se aplicam os requisitos operacionais para estabelecimento de cotas de emprego específicas, programas de negócios dedicados ou conselhos de monitoramento conjunto, sendo o relacionamento gerido na esfera institucional e de proteção de direitos.', 'B'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'COMUNIDADE-03', 'needs_revision'::requirement_status, 'non_conforming'::assessment_score, 0, 'Aderencia calculada: sem dados. Nivel de maturidade declarado: B. Lacunas identificadas: Os itens referentes à colaboração econômica direta, co-design de processos, acordos de benefícios mútuos e gestão compartilhada foram avaliados como Não Aplicáveis (N/A). Esta classificação baseia-se nos estudos socioambientais (EIA/RIMA e Relatório AIDH), que confirmam a ausência de comunidades indígenas ou quilombolas vivendo na Área de Influência Direta (AID) imediata da mina. Devido à inexistência de impacto direto de deslocamento ou interferência no modo de vida diário dessas comunidades, não se aplicam os requisitos operacionais para estabelecimento de cotas de emprego específicas, programas de negócios dedicados ou conselhos de monitoramento conjunto, sendo o relacionamento gerido na esfera institucional e de proteção de direitos.', 'B'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'COMUNIDADE-03', 'approved'::requirement_status, 'fully_conforming'::assessment_score, 100, 'Aderencia calculada: 100.0%. Nivel de maturidade declarado: B. Lacunas identificadas: Os itens referentes à colaboração econômica direta, co-design de processos, acordos de benefícios mútuos e gestão compartilhada foram avaliados como Não Aplicáveis (N/A). Esta classificação baseia-se nos estudos socioambientais (EIA/RIMA e Relatório AIDH), que confirmam a ausência de comunidades indígenas ou quilombolas vivendo na Área de Influência Direta (AID) imediata da mina. Devido à inexistência de impacto direto de deslocamento ou interferência no modo de vida diário dessas comunidades, não se aplicam os requisitos operacionais para estabelecimento de cotas de emprego específicas, programas de negócios dedicados ou conselhos de monitoramento conjunto, sendo o relacionamento gerido na esfera institucional e de proteção de direitos.', 'B'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'COMUNIDADE-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna, não ficou evidenciado que o  modelo de gestão incorpora a tomada de decisão colaborativa (Governança Compartilhada), requisito essencial para os níveis de excelência. Embora a comunidade seja ouvida na priorização, as decisões finais sobre estratégias de mitigação, direcionamento de investimentos sociais e avaliação de eficácia permanecem centralizadas na empresa. Além disso, faltam processos de parceria para a gestão do legado e preparação da comunidade para a autonomia no período pós-fechamento.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'COMUNIDADE-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna, não ficou evidenciado que o  modelo de gestão incorpora a tomada de decisão colaborativa (Governança Compartilhada), requisito essencial para os níveis de excelência. Embora a comunidade seja ouvida na priorização, as decisões finais sobre estratégias de mitigação, direcionamento de investimentos sociais e avaliação de eficácia permanecem centralizadas na empresa. Além disso, faltam processos de parceria para a gestão do legado e preparação da comunidade para a autonomia no período pós-fechamento.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'COMUNIDADE-04', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 74.1%. Nivel de maturidade declarado: A. Lacunas identificadas: Como lacuna, não ficou evidenciado que o  modelo de gestão incorpora a tomada de decisão colaborativa (Governança Compartilhada), requisito essencial para os níveis de excelência. Embora a comunidade seja ouvida na priorização, as decisões finais sobre estratégias de mitigação, direcionamento de investimentos sociais e avaliação de eficácia permanecem centralizadas na empresa. Além disso, faltam processos de parceria para a gestão do legado e preparação da comunidade para a autonomia no período pós-fechamento.', 'A'),
  ('ed11af20-6ce7-4f19-b0b8-527e0ffd951b'::uuid, 'COMUNIDADE-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 72.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Foi identificado que o sistema apresenta lacunas nos requisitos de engajamento avançado. O mecanismo foi desenvolvido  sem evidência de design colaborativo com a CDI afetada. Adicionalmente, o processo encerra-se na entrega da resposta, não sendo identificado um fluxo formal de follow-up com os usuários para verificar a satisfação final, nem uma revisão estruturada da eficácia global do sistema que tenha gerado ações corretivas baseadas na percepção da comunidade.', 'A'),
  ('0e6db5e4-be92-4dfd-86d5-c3e63171e973'::uuid, 'COMUNIDADE-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 72.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Foi identificado que o sistema apresenta lacunas nos requisitos de engajamento avançado. O mecanismo foi desenvolvido  sem evidência de design colaborativo com a CDI afetada. Adicionalmente, o processo encerra-se na entrega da resposta, não sendo identificado um fluxo formal de follow-up com os usuários para verificar a satisfação final, nem uma revisão estruturada da eficácia global do sistema que tenha gerado ações corretivas baseadas na percepção da comunidade.', 'A'),
  ('c9ebe409-535a-4fda-aaa7-8899292e7b8a'::uuid, 'COMUNIDADE-05', 'needs_revision'::requirement_status, 'partially_conforming'::assessment_score, 50, 'Aderencia calculada: 72.7%. Nivel de maturidade declarado: A. Lacunas identificadas: Foi identificado que o sistema apresenta lacunas nos requisitos de engajamento avançado. O mecanismo foi desenvolvido  sem evidência de design colaborativo com a CDI afetada. Adicionalmente, o processo encerra-se na entrega da resposta, não sendo identificado um fluxo formal de follow-up com os usuários para verificar a satisfação final, nem uma revisão estruturada da eficácia global do sistema que tenha gerado ações corretivas baseadas na percepção da comunidade.', 'A')
),
resolved as (
  select '637aa7f4-5332-4a1d-946f-9ab77219fde4'::uuid as cycle_id, raw.facility_id, sr.id as requirement_id,
    raw.status, raw.score, raw.score_value, raw.assessment_text, raw.maturity_level
  from raw
  join standard_requirements sr on sr.code = raw.requirement_code and sr.standard_id = 2
),
inserted_responses as (
  insert into tsm_responses (cycle_id, facility_id, requirement_id, status, implementation_text, submitted_at)
  select resolved.cycle_id, resolved.facility_id, resolved.requirement_id, resolved.status,
    'Importado da avaliacao tecnica HIDROBR (doc. HBR101550001-GMN-RT001, Rev.1, 08/07/2026, Apendice II TSM).',
    now()
  from resolved
  returning id, facility_id, requirement_id
)
insert into tsm_assessments (response_id, assessed_by, score, score_value, assessment_text, maturity_level, published_at)
select ir.id, (select assessed_by from assessor), res.score, res.score_value, res.assessment_text, res.maturity_level,
  '2026-07-08 00:00:00-03'::timestamptz
from inserted_responses ir
join resolved res on res.facility_id = ir.facility_id and res.requirement_id = ir.requirement_id;
commit;